# Generated by Django 4.0.3 on 2022-03-06 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
