# Generated by Django 4.0.3 on 2022-03-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_user'),
        ('images', '0003_alter_image_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_images', to='user_profile.userprofile'),
        ),
    ]
